# Generated by Django 5.0 on 2024-01-26 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_bases', '0001_initial'),
        ('products_options_values', '0001_initial'),
        ('products_stock', '0002_alter_productstock_product_option_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='product_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='products_bases.productbase'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product_option_value',
            field=models.ManyToManyField(related_name='product_stock', to='products_options_values.productoptionvalue'),
        ),
    ]
