# Generated by Django 5.0 on 2024-01-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tag', models.CharField(max_length=255)),
                ('unity', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
