# Generated by Django 5.0 on 2024-01-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='tag',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoption',
            name='unity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
