# Generated by Django 5.0 on 2024-01-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_options', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='unity',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
