# Generated by Django 5.0 on 2024-01-13 01:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_options', '0002_alter_productoption_unity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
