# Generated by Django 5.0 on 2024-01-01 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_attributes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsAttributesValues',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_attributes.productattribute')),
            ],
        ),
    ]
