# Generated by Django 5.0 on 2024-01-06 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_options', '0002_productoption_tag_productoption_unity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_options.productoption')),
            ],
        ),
    ]
